acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.userlogin, name="login"),
    path('logout/', views.userlogout, name="logout"),
    path('profile/',views.profile, name='profile'),
    path('signup/',views.signup, name='signup'),
    path('update/',views.update, name='update'),
    path('delete/',views.delete,name='delete'),
    path('chpass',views.chpass,name='chpass')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/',include('trans.urls')),
    path('tts/',include('tts.urls')),
    path('edit/',include('edit.urls')),
    path('vote/',include('vote.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.urls import path
from . import views

app_name='vote'
urlpatterns=[
    path('index/',views.index,name='index'),
    path('detail/<tpk>',views.detail,name='detail'),
    path('vote/<tpk>',views.vote , name='vote'),
    path('creeate/', views.create, name='create')

    
]

vote/models.py
from django.db import models
from acc.models import User
# Create your models here.
class Topic(models.Model):
    subject = models.CharField(max_length=100)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name='maker')
    content = models.TextField()
    voter = models.ManyToManyField(User, blank=True, related_name='voter')
    
    
    def __str__(self):
        return self.subject
    
class Choice(models.Model):
    top = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    num = models.IntegerField(default=0)
    pic = models.ImageField(upload_to='media/',default='')
    com = models.TextField(default="")
    choicer = models.ManyToManyField(User,blank=True)
    
    def __str__(self):
        return f"{self.top}_{self.name}"

    def getpic(self):
        if self.pic:
            return self.pic.url
        return "/media/noimage.png"
    
    

vote/views.py
from django.shortcuts import render,redirect
from .models import Choice, Topic

# Create your views here.
def index(reqeust):
    t= Topic.objects.all()
    context = {
        'tset':t
    }
    
    return render(reqeust, 'vote/index.html',context)

def detail(request, tpk):
    t = Topic.objects.get(id=tpk)
    c = t.choice_set.all()
    context = {
        "t" : t,
        "cset" : c
    }
    return render(request, "vote/detail.html", context)


def vote(request, tpk):
    t = Topic.objects.get(id=tpk)
    if not request.user in t.voter.all():
        t.voter.add(request.user)
        cpk = request.POST.get("cho")
        c = Choice.objects.get(id=cpk)
        c.num += 1
        c.save()
    return redirect("vote:detail", tpk)


def create(request):
    if request.method == 'POST':
        s=request.POST.get('sub')
        c=request.POST.get('con')
        cho=request.POST.getlist('cho')
        pi=request.FILES.get('pic')
        t=Topic(subject=s, content=c, maker=request.user)
        t.save()
        for i in cho:
            Choice(top=t,name=i, pic=pi).save()
        return redirect('vote:index')
    return render(request, 'vote/create.html')

templates/vote/create.html
{%extends 'base.html'%}
{%block con%}

<h1><b> 토픽 생성 </b></h1>
<form method="post">
    {%csrf_token%}
    <input type="text" placeholder="주제 입력" name="sub"><br><br>
    <textarea name="con" id="" cols="30" rows="3"placeholder='내용 입력'></textarea><br><br>
    <hr>
    <button type="button" onclick="makecho()" class="btn btn-dark">보기추가</button><br><br>
    <button class="btn btn-dark">토픽생성</button>
    <div id="here"></div>
</form>
<script> 
    function makecho(){
        d = document.getElementById('here');
        p = document.createElement('p');
        p.innerHTML = " 보기이름 <input name='cho' type='text'><br><input name ='pic' type='file' placeholder='사진첨부'>";
        d.appendChild(p);
    }
</script>
{%endblock%}

templates/vote/detail.html
{% extends 'base.html'%}

{%block con%}
{%load mathfilters%}


<h2>{{t.subject}}</h2><br>


<h4>게시자 . <b>{{t.maker}}</b></h4>



<br><hr><br>
{% if user in t.voter.all %}
    <h5> 투표 결과 </h5>
        <div class="row">
            {%for i in cset%}
                <div class="col-sm-6">
                    <img src="{{i.getpic}}" name="cho" width="50%"><br>
                    {{i.name}} {{i.num|div:t.voter.count|mul:100|floatformat:2}} %<br><br>
                </div>
            {%endfor%}
        </div>  

{% else%}

    <form method="post" action="{%url 'vote:vote' t.id %}">
        {%csrf_token%}
        <div class="row">
        {%for i in cset%}
            <div class="col-sm-6">
                <img src="{{i.pic}}" name="cho" width="50%"><br>
                <input type="radio" name="cho" value="{{i.id}}" {%if forloop.first %} checked{%endif%}> {{i.name}} 
            </div>
        {%endfor%}
        </div>
        <br>
        <button class="btn btn-dark">투표하기</button>
    </form>
    {{c.pic}}
{%endif%}

{%endblock%}

100*투표자/총원

투표자/총원*100

3*2

templates/vote/index.html
{% extends 'base.html'%}
{% block con %}
    <a href="{%url 'vote:create'%}"><button class="btn btn-dark">토픽생성</button></a><br><br>

    {%for i in tset%}
        {%if user in i.voter.all %}
        <div>
            <img src="{{i.maker.getpic}}" width="10%"><br><br>
            {{i.maker}}님의 글
        </div>
        <hr>
            <a href="{%url 'vote:detail' i.id%}"><button class="btn btn-dark">{{i.subject}} 결과보기</button></a> ✔<br><br>
            <hr>
        {%else%}
            <img src="{{i.maker.getpic}}" width="10%"><br><br>
            {{i.maker}}님의 글
            <a href="{%url 'vote:detail' i.id%}"><button class="btn btn-dark">{{i.subject}}</button></a><br><br>
            <hr>
        {%endif%}
    {%endfor%}


{% endblock%}