acc/urls.py
from django.urls import path
from . import views

app_name = "acc"
urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.userlogin, name="login"),
    path('logout/', views.userlogout, name="logout"),
    path('profile/',views.profile, name='profile'),
    path('signup/',views.signup, name='signup'),
    path('update/',views.update, name='update'),
    path('delete/',views.delete,name='delete'),
    path('chpass',views.chpass,name='chpass')
]

board/urls.py
from django.urls import path
from . import views

app_name='board'
urlpatterns=[
    path('index/',views.index,name='index'),
    path('detail/<bpk>',views.detail, name='detail'),
    path('update/<bpk>',views.update,name='update'),
    path('delete/<bpk>',views.delete,name='delete'),
    path('create/',views.create, name='create'),
    path('crepl/<bpk>',views.crepl,name='crepl'),
    path('cdelete/<bpk>/<rpk>',views.cdelete, name='cdelete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/',include('trans.urls')),
    path('tts/',include('tts.urls')),
    path('edit/',include('edit.urls')),
    path('vote/',include('vote.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from acc.models import User
# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="writer")
    content = models.TextField()
    pubdate = models.DateTimeField()
    likey = models.ManyToManyField(User, blank=True, related_name="likey")

    def __str__(self):
        return self.subject


class Reply(models.Model):
    board = models.ForeignKey(Board,on_delete=models.CASCADE)
    replyer = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models. TextField()

    def __str__(self):
        return f"{self.board}글의 {self.replyer} 님의 댓글"

board/views.py
from django.shortcuts import render,redirect
from .models import Board,Reply
from django.utils import timezone
from django.core.paginator import Paginator


def index(request):
    cate=request.GET.get('cate',"")
    kw=request.GET.get('kw',"")
    pg=request.GET.get('page',1)
    if kw:
        if cate == 'sub':
            b=Board.objects.filter(subject__startswith =kw)
        elif cate == 'con':
            b=Board.objects.filter(content__contains = kw)
        elif cate == 'wri':
            try:
                from acc.models import User
                u=User.objects.get(username=kw)
                b=Board.objects.filter(writer=u)
            except:
                b=Board.objects.none()
    else:
        b=Board.objects.all()
    b=b.order_by('-pubdate')    
    pag = Paginator(b,3)
    obj=pag.get_page(pg)
    context={
        'bset':obj,
        'cate':cate,
        'kw':kw
    }
    return render(request,'board/index.html',context)


def detail(request,bpk):
    b=Board.objects.get(id=bpk)
    r=b.reply_set.all()

    context={
        'b':b,
        'rset':r
    }
    return render(request, 'board/detail.html',context)

def update(request,bpk):
    b=Board.objects.get(id=bpk)
    if b.writer!=request.user:
        #작성자가 아니야
        return redirect('board:index')
        
    if request.method=="POST":
        s = request.POST.get("sub")
        c = request.POST.get("con")
        b.subject, b.content = s,c
        b.save()
        return redirect("board:detail", bpk)
    
    context={
        'b' :b
    }
    return render(request, 'board/update.html',context)

def delete(request,bpk):
    b=Board.objects.get(id=bpk)
    if b.writer == request.user:
        b.delete()
    else:
        pass
    return redirect('board:index')

def create(request):
    if request.method=='POST':
        s=request.POST.get('sub')
        c=request.POST.get('con')
        Board(subject=s,content=c, writer=request.user ,pubdate=timezone.now()).save()
        return redirect('board:index')
    return render(request, 'board/create.html')

def crepl(request,bpk):
    b=Board.objects.get(id=bpk)
    c=request.POST.get('ncom')
    Reply(board=b,comment=c,replyer=request.user).save()
    return redirect('board:detail',bpk)

def cdelete(request,bpk,rpk):
    r=Reply.objects.get(id=rpk)
    if r.replyer==request.user:
        r.delete()
    else:
        pass
    return redirect("board:detail",bpk)

templates/board/create.html
{%extends 'base.html'%}
<!-- board/create.html -->
{%block con%}
<h1><b>게시글 작성</b></h1>
<form method="post" enctype="multipart/form-data">
    {%csrf_token%}
    <div class="mb-3 mt-5">
        <label class="form-label"><b>SUBJECT</b></label>
        <input name='sub'' type="text" class="form-control">
    </div>
    <div class="mb-3">
        <label class="form-label"><b>WRITER</b></label>
        <input type="text" class="form-control" value="{{ user }}" disabled>
    </div>    
    <div class="mb-3">
        <label class="form-label"><b>CONTENT</b></label>
        <textarea name='con' class="form-control" style="height: 150px;"></textarea>
    </div>
    <div class="text-end mt-3">
        <button class="btn btn-dark">생성</button>
    </div>
</form>
{%endblock%}

templates/board/detail.html
{%extends 'base.html'%}
{%block con%}



<div class="row mt-5">
    <table>
        <tr>
            <th rowspan="4">
                <div class="col-sm-3 m-3" >
                    <img src="{{b.writer.getpic}}" width=90px>
                </div>
            </th>
            <th>
                <b>제목 : {{b.subject}}</b>
            </th>
            <tr>
                <th>
                    <div class="text-left mt-3">
                        작성자 : <b>{{b.writer}}
                    </div>
                </th>
            </tr>
            <tr>
                <th>
                    <div class="text-left mt-3">
                        작성일 : <b> {{ b.pubdate | date:'Y년 n월 j일 / H:i' }}</b>
                    </div>
                </th>
            </tr>
    </table>
    <div class="col-sm-9">
        <textarea class="form-control" style="height:250px" disabled>{{b.content}}</textarea>
    </div>
</div>

<div class="text-end mt-4">
    <a href="{% url 'board:index'%}" class="btn btn-dark">글목록</a>
    {% if b.writer == user %}
        <a href="{% url 'board:update' b.id%}" class="btn btn-dark">글수정</a>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#remove">
            글삭제
        </button>
    {%endif%}

</div>


<!-- Modal -->
<div class="modal fade" id="remove" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><b>게시글 삭제 알림창</b></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                정말 삭제하시겠습니까?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                <a href="{%url 'board:delete' b.id%}" class="btn btn-danger">삭제</a>
            </div>
        </div>
    </div>
</div>
<hr>
    <form method="post" action="{% url 'board:crepl' b.id%}">
        {%csrf_token%}
        <div class="row">
            <div class="col-sm-10">
                <input name="ncom" type="text" class="form-control" placeholder="댓글을 남겨주세요">
            </div>
            <div class="col-sm-2">
                <div class="text-end">
                    <button class="btn btn-dark">댓글작성</button>
                </div>
            </div>
        </div>
    </form>

{%for i in rset%}
    <table class="mb-3">
        <tr>
            <th width="45px"> <img src="{{i.replyer.getpic}}" width="30px" class="rounded-circle"></th>
            <th width="80px"> {{i.replyer}}</th>
            <th width="400px" style="text-align: left;"> {{i.comment}} 
                {%if user == i.replyer %}
                <a style="color: gray; text-decoration: none;" href="{% url 'board:cdelete' b.id i.id %}">x</a>
                {%endif%}
            </th>
        </tr>
        <hr>
    </table>
{%empty%}
    <div class="mt-5"> 댓글이 없습니다.</div>
{%endfor%}





{%endblock%}

templates/board/index.html
{%extends 'base.html'%}
{%load mathfilters%}
{%block con%}
<h1><b>게시판</b></h1>
    
<div class="text-end">
    <a href="{%url 'board:create'%}" class="btn btn-dark">게시글생성</a>
</div>

<table class="table table-hover mt-4">
    <thead>
        <tr class="table-dark">
            <th scope="col">NO</th>
            <th scope="col">SUBJECT</th>
            <th scope="col">SUMMARY</th>
            <th scope="col">WRITER</th>
            <th scope="col">LIKEY</th>
        </tr>
    </thead>
    <tbody>
       {%for i in bset%}
        <tr>
            <th scope="row">{{bset.start_index|add:forloop.counter0}}</th>
            <td><a class="sub" href="{%url 'board:detail' i.id%}">{{i.subject}}</a></td>
            <td>{{i.content|truncatewords:3}}</td>
            <td>{{i.writer}}</td>
            <td>0</td>
        </tr>
        {%empty%}
        <tr>
            <th colspan="5">                 
                {%if kw%}
                검색결과가 없음 
            
                {%else%}
                게시물이 아예 없음
            
                {%endif%}
            </th>
        </tr>
        {%endfor%}
    </tbody>
</table>
<div class="text-center">
    {% if bset.has_previous %}
        <a href="{%url 'board:index'%}?page=1"> <button>1</button></a>
        <a href="{%url 'board:index'%}?page={{bset.previous_page_number}}&cate={{cate}}&kw={{kw}}"><button><</button></a>
    {%else%}
        <button disabled>1</button>
        <button disabled><</button>
    {%endif%}
    {% for i in bset.paginator.page_range%}
        {% if i >= bset.number|sub:4 and bset.number|add:5 >= i %}
            <a href="{% url 'board:index'%}?page={{i}}&cate={{cate}}&kw={{kw}}"> <button style="border: none; background-color: inherit;" {% if bset.number == i %} disabled {%endif%}>{{i}}</button></a>
        {%endif%}
    {%endfor%}


    {%if bset.has_next%}
        <a href="{%url 'board:index'%}?page={{bset.next_page_number}}&cate={{cate}}&kw={{kw}}"> <button>></button></a>
        <a href="{%url 'board:index'%}?page={{bset.paginator.num_pages}}&cate={{cate}}&kw={{kw}}"><button>{{bset.paginator.num_pages}}</button></a>
    {%else%}
        <button disabled>></button>
        <button disabled>{{bset.paginator.num_pages}}</button>
    {%endif%}
</div>

<style>
    .sub {
        text-decoration: none;
        color:black;
        font-weight: bold;
    }
    .sub:hover{
        color:red;
    }
</style>
<form>
    <div class="row">
        <div class='col-sm-2 mt-3'>
            <select name="cate" class="form-select" aria-label="Default select example">
                <option value="sub" {%if cate == 'sub' %} selected {%endif%}>제목</option>
                <option value="wri" {%if cate == 'wri' %} selected {%endif%}>작성자</option>
                <option value="con" {%if cate == 'con' %} selected {%endif%}>내용</option>
            </select>
        </div>

        <div class="col-sm-8 mb-3 mt-3">
            <input size="50" value="{{kw}}" name="kw" type="text" class="form-control " placeholder="검색어를 입력하세요" aria-label="Recipient's username" aria-describedby="button-addon2">
        </div>

        <div class="col-sm-2 mt-3">
            <button class="btn btn-outline-secondary" id="button-addon2">검색</button>
        </div>
    </div>
</form>


{%endblock%}

templates/board/update.html
{% extends 'base.html' %}
{% block con %}

    <h1><b>게시글수정</b></h1>

    <form method="post">
        {% csrf_token %}
        <div class="mb-3 mt-5">
            <label class="form-label"><b>SUBJECT</b></label>
            <input type="text" value="{{ b.subject }}" name="sub" class="form-control">
        </div>
        <div class="mb-3">
            <label class="form-label"><b>WRITER</b></label>
            <input type="text" class="form-control" disabled value="{{ b.writer }}">
        </div>
        <div class="mb-3">
            <label class="form-label"><b>CONTENT</b></label>
            <textarea class="form-control" name="con" style="height: 150px;">{{ b.content }}</textarea>
        </div>
        <div class="text-end mt-3">
            <button class="btn btn-dark">수정</button>
        </div> 
    </form>
{% endblock %}